### ISSUE TITLE
支付后无法下载源码

### ISSUE THREAD

**Issue by user080975** [byteee-fund/bsf-crowdfunding-plan#4]
支付后，后台无法下载源码包。可以提供正确链接吗？多谢
![2024-01-25 at 13 03 14](https://github.com/byteee-fund/bsf-crowdfunding-plan/assets/54892636/bda37f67-dc8b-4477-9660-6d4dfc2c2759)

![2024-01-25 at 13 12 08](https://github.com/byteee-fund/bsf-crowdfunding-plan/assets/54892636/15a68c9a-d9e8-4bcc-8b48-6b7f013d2ca6)

**Comment by jasonz1987** [comment]
Processed
